### ISSUE TITLE
negative durability causes issues with FlightAssistant

### ISSUE THREAD

**Issue by IMB11** [sylenthuntress/Unbreakable#4]
https://discord.com/channels/507304429255393322/1314988095501766697/1319741975381151846

![image](https://github.com/user-attachments/assets/2836b90b-cb4d-407b-b262-33081fee288b)

This might be an issue with it using actual negative values to represent negative durability.

**Comment by sylenthuntress** [comment]
I see the issue, but I have no idea how to fix it since the issue is seemingly with them throwing an error instead of clamping. I could disable the feature for elytras if the mod is installed, but that seems unintuitive. I'll try to find a fix ASAP, but in the meantime, it can be "fixed" with a datapack tag to exclude elytras.
